/* CLAYTON — Dossier player
   Uses manifest.json generated by your script
*/

const $ = (sel) => document.querySelector(sel);

const audio = $("#audio");
const playBtn = $("#playBtn");
const playIcon = playBtn.querySelector(".playBtn__icon");
const nowTitle = $("#nowTitle");
const nowMeta = $("#nowMeta");
const seek = $("#seek");
const tCur = $("#tCur");
const tDur = $("#tDur");
const trackList = $("#trackList");
const photo = $("#photo");
const shufflePhotoBtn = $("#shufflePhoto");
const nextBtn = $("#nextBtn");
const galleryGrid = $("#galleryGrid");

const yearEl = $("#year");
yearEl.textContent = new Date().getFullYear();

let manifest = null;
let imagePool = [];
let groups = {};
let currentGroup = "finished";
let currentIndex = -1;
let currentTracks = [];

function safeUrl(path) {
  // Handles spaces etc. Avoids breaking Netlify URLs.
  return encodeURI(path);
}

function prettifyTitle(filename) {
  const decoded = decodeURIComponent(filename);
  const base = decoded.replace(/\.[^/.]+$/, ""); // remove extension
  return base
    .replace(/[_]+/g, " ")
    .replace(/\s+/g, " ")
    .replace(/^\d+\s*[-_.]?\s*/g, "") // remove leading numbers
    .trim();
}

function fmtTime(sec) {
  if (!isFinite(sec) || sec < 0) return "0:00";
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

function setPlayUI(isPlaying) {
  playBtn.classList.toggle("is-playing", isPlaying);
  playIcon.textContent = isPlaying ? "❚❚" : "▶";
  playIcon.style.marginLeft = isPlaying ? "0px" : "3px";
}

function pickRandomPhoto() {
  if (!imagePool.length) return;
  const src = safeUrl(imagePool[Math.floor(Math.random() * imagePool.length)]);
  photo.classList.remove("is-ready");
  photo.onload = () => photo.classList.add("is-ready");
  photo.src = src;
}

function renderTabs() {
  const tabs = document.querySelectorAll(".tab");
  tabs.forEach((t) => {
    const g = t.dataset.group;
    // Hide tabs that don't exist in manifest
    if (!groups[g] || groups[g].length === 0) {
      t.style.display = "none";
      return;
    }
    t.style.display = "";
    t.classList.toggle("is-active", g === currentGroup);
    t.onclick = () => {
      currentGroup = g;
      tabs.forEach((x) => x.classList.remove("is-active"));
      t.classList.add("is-active");
      loadGroup(g);
    };
  });
}

function renderTrackList(tracks) {
  trackList.innerHTML = "";
  tracks.forEach((tr, idx) => {
    const btn = document.createElement("button");
    btn.className = "track";
    btn.type = "button";
    btn.innerHTML = `
      <div>
        <div class="track__title">${tr.title}</div>
        <div class="track__sub">${tr.groupLabel}</div>
      </div>
      <div class="track__right">${idx === currentIndex ? "•" : ""}</div>
    `;
    btn.onclick = () => playIndex(idx);
    trackList.appendChild(btn);
  });

  highlightActive();
}

function highlightActive() {
  const items = trackList.querySelectorAll(".track");
  items.forEach((el, i) => {
    el.classList.toggle("is-active", i === currentIndex);
    const right = el.querySelector(".track__right");
    if (right) right.textContent = i === currentIndex ? "PLAYING" : "";
  });
}

function playIndex(idx) {
  if (!currentTracks.length) return;
  currentIndex = idx;

  const tr = currentTracks[currentIndex];
  audio.src = safeUrl(tr.path);
  audio.play().catch(() => {});
  nowTitle.textContent = tr.title;
  nowMeta.textContent = tr.groupLabel;

  pickRandomPhoto();
  highlightActive();
}

function nextTrack() {
  if (!currentTracks.length) return;
  const next = (currentIndex + 1) % currentTracks.length;
  playIndex(next);
}

function loadGroup(groupKey) {
  const list = (groups[groupKey] || []).map((path) => {
    const filename = path.split("/").pop();
    const title = prettifyTitle(filename);
    return {
      path,
      title,
      groupLabel: groupKey.toUpperCase(),
    };
  });

  currentTracks = list;
  currentIndex = -1;
  renderTrackList(currentTracks);

  // Auto-select first track but do NOT auto-play (user presses play)
  if (currentTracks[0]) {
    nowTitle.textContent = currentTracks[0].title;
    nowMeta.textContent = currentTracks[0].groupLabel;
  }
}

function buildImagePool(m) {
  const imgs = m.images || {};
  const pool = [];
  Object.keys(imgs).forEach((k) => {
    (imgs[k] || []).forEach((p) => pool.push(p));
  });
  return pool;
}

function buildGroups(m) {
  const aud = m.audio || {};
  const out = {};

  // Normalize whatever keys exist in your manifest (you’ve had a few folder names)
  // We map them into the 3 UI tabs we want.
  const finished = []
    .concat(aud.finished || [])
    .concat(aud["finished-tracks"] || []);
  const demos = []
    .concat(aud.demos || [])
    .concat(aud["day1-demos"] || [])
    .concat(aud["day-1-demos"] || []);
  const boardtapes = []
    .concat(aud.boardtapes || [])
    .concat(aud["board-tapes"] || [])
    .concat(aud["boardtapes"] || []);

  out.finished = finished;
  out.demos = demos;
  out.boardtapes = boardtapes;

  return out;
}

function renderGallery() {
  if (!imagePool.length) return;
  galleryGrid.innerHTML = "";

  // Show a solid chunk, not everything (keeps it fast).
  // You can bump this up later.
  const max = Math.min(imagePool.length, 60);

  // Shuffle
  const shuffled = [...imagePool].sort(() => Math.random() - 0.5).slice(0, max);

  shuffled.forEach((src) => {
    const div = document.createElement("div");
    div.className = "gItem";
    const img = document.createElement("img");
    img.loading = "lazy";
    img.alt = "CLAYTON image";
    img.src = safeUrl(src);
    div.appendChild(img);
    galleryGrid.appendChild(div);
  });
}

function togglePlay() {
  if (!audio.src) {
    // If nothing loaded, choose the first track in current group
    if (!currentTracks.length) return;
    playIndex(0);
    return;
  }
  if (audio.paused) audio.play().catch(() => {});
  else audio.pause();
}

function wireUI() {
  playBtn.addEventListener("click", togglePlay);

  shufflePhotoBtn.addEventListener("click", () => pickRandomPhoto());
  nextBtn.addEventListener("click", () => nextTrack());

  // keyboard: space = play/pause
  window.addEventListener("keydown", (e) => {
    const tag = (e.target && e.target.tagName || "").toLowerCase();
    if (tag === "input" || tag === "textarea") return;
    if (e.code === "Space") {
      e.preventDefault();
      togglePlay();
    }
    if (e.code === "ArrowRight") nextTrack();
  });

  // audio events
  audio.addEventListener("play", () => setPlayUI(true));
  audio.addEventListener("pause", () => setPlayUI(false));
  audio.addEventListener("ended", () => nextTrack());

  audio.addEventListener("loadedmetadata", () => {
    tDur.textContent = fmtTime(audio.duration);
  });

  audio.addEventListener("timeupdate", () => {
    tCur.textContent = fmtTime(audio.currentTime);
    if (audio.duration) {
      const pct = (audio.currentTime / audio.duration) * 100;
      seek.value = String(pct);
    }
  });

  seek.addEventListener("input", () => {
    if (!audio.duration) return;
    const pct = Number(seek.value) / 100;
    audio.currentTime = pct * audio.duration;
  });

  // smooth hash scroll
  window.addEventListener("hashchange", () => {
    const id = location.hash.replace("#", "");
    if (!id) return;
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  });
}

async function init() {
  wireUI();

  // Load manifest
  const res = await fetch("manifest.json", { cache: "no-store" });
  manifest = await res.json();

  imagePool = buildImagePool(manifest);
  groups = buildGroups(manifest);

  renderTabs();
  loadGroup(currentGroup);

  // Pick a starting visual
  pickRandomPhoto();

  // Gallery
  renderGallery();
}

init().catch((err) => {
  console.error(err);
  nowTitle.textContent = "manifest.json not found / failed to load";
  nowMeta.textContent = "Check Netlify deploy + file paths";
});
